version: "3.8"
services:
  postgres-local-instance:
    image: postgres:14.5-alpine
    container_name: postgres-server-local
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - store-postgres-data-local:/var/lib/postgresql/data
    networks:
      - net-postgres-local

  pgadmin-local-instance:
    image: dpage/pgadmin4:6.12
    container_name: pgadmin
    restart: on-failure
    ports:
      - 8085:80
    depends_on:
      - postgres-local-instance
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@marcoshssilva.com.br
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    volumes:
      - store-pgadmin-data-local:/var/lib/pgadmin
    networks:
      - net-postgres-local

  redis-cache-local:
    image: redis:6.2-alpine
    container_name: redis-server
    restart: on-failure
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel debug
    volumes: 
      - store-redis-data-local:/data
    networks:
      - net-redis-local

  rabbitmq-local:
    image: rabbitmq:3.10.23-management-alpine
    container_name: rabbitmq-broker
    restart: on-failure
    ports:
      - '5672:5672'
      - '15672:15672'
      - '15692:15692'
      - '4369:4369'
      - '25672:25672'
    volumes:
        - store-rabbit-data:/var/lib/rabbitmq
        - store-rabbit-logs:/var/log/rabbitmq
    networks:
      - net-rabbitmq-local

  mongo:
    image: mongo:6.0.5
    container_name: mongodb-server
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - store-mongodb-data:/data/db
    ports:
      - '27017:27017'
    networks:
      - net-mongodb-local
  
#  mongo-express:
#    image: mongo-express
#    container_name: mongo-express-web
#    restart: always # to fix restart when mongodb is not up
#    ports:
#      - '8086:8081'
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
#      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
#      ME_CONFIG_MONGODB_URL: mongodb://root:secret@mongo:27017/
#    networks:
#      - net-mongodb-local
#    depends_on:
#      - mongo

  spider-mail-archiever:
    image: marcoshssilva/custom-spider-mail-server:latest
    container_name: spider-mail-archiever
    restart: on-failure
    ports:
      - '25:25'
      - '993:993'
      - '8087:8080'
    volumes:
      - store-spider-mail-archiever-data:/opt/spider
    networks:
      - net-spider-mail-archiever-local

#   roundcube-mail:
#     image: roundcube/roundcubemail
#     container_name: 'roundcube'
#     restart: on-failure
#     ports:
#       - 8088:80
#     environment:
#       ROUNDCUBEMAIL_DEFAULT_HOST: tls://host.docker.internal
#       ROUNDCUBEMAIL_DEFAULT_PORT: 993
#       ROUNDCUBEMAIL_SMTP_SERVER: tls://host.docker.internal
#       ROUNDCUBEMAIL_SMTP_PORT: 25
#       ROUNDCUBEMAIL_DB_TYPE: pgsql
#       ROUNDCUBEMAIL_DB_HOST: postgres-local-instance
#       ROUNDCUBEMAIL_DB_PORT: 5432
#       ROUNDCUBEMAIL_DB_NAME: roundcubemail
#       ROUNDCUBEMAIL_DB_USER: postgres
#       ROUNDCUBEMAIL_DB_PASSWORD: postgres
#     networks:
#       - net-spider-mail-archiever-local
#       - net-postgres-local
  
volumes:
  store-postgres-data-local:
    driver: local
  store-pgadmin-data-local:
    driver: local
  store-redis-data-local:
    driver: local
  store-rabbit-data:
    driver: local
  store-rabbit-logs:
    driver: local
  store-mongodb-data:
    driver: local
  store-spider-mail-archiever-data:
    driver: local

networks:
  net-postgres-local:
    driver: bridge
  net-redis-local:
    driver: bridge
  net-rabbitmq-local:
    driver: bridge
  net-mongodb-local:
    driver: bridge
  net-spider-mail-archiever-local:
    driver: bridge
